sudo: true

os:
  - linux
  - osx

language: node_js

node_js:
  - 6
  - 8
  - 10

env:
  global:
    - CC=clang
    - CXX=clang++
    - npm_config_clang=1

git:
  depth: 10

compiler: clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p; fi

install:
  - npm install

script:
  - npm test
